/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.votingsystem;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author hp
 */
public class Form7 extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form Form7
     */
    Statement stmt,stmt1;
    Connection con;
    static JLabel j;
    ImageIcon icon;
    public Form7() throws ClassNotFoundException, SQLException {
        initComponents();
        icon=new ImageIcon("C:/Users/Oem/Documents/NetBeansProjects/com.mycompany_VotingSystem_jar_1.0-SNAPSHOT/src/main/java/com/mycompany/votingsystem/Images/images.png");
        setIconImage(icon.getImage());
         setExtendedState(JFrame.MAXIMIZED_BOTH);
        getContentPane().setBackground(new Color(255,255,51));
       /* addWindowListener(new WinClose()); */
        jLabel12.setVisible(false);
         jLabel13.setVisible(false);
          jLabel14.setVisible(false);
           jLabel15.setVisible(false);
            jLabel10.setVisible(false);
        Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/votingsystem","root","Pritpal@1999");
        
        stmt=con.createStatement();
        stmt1=con.createStatement();
    }
    
        public void run() 
	{
		int i=0;
		while(i<10)
		{
			if(i%2==0)
			{
				j.setVisible(true);
			}
			else
			{
				j.setVisible(false);
			}
			i++;
			try
			{
				Thread.sleep(1000);
			}				
			catch(InterruptedException e)
			{}
			
		}
               
        try {
            new Form6().setVisible(true);
            dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Form7.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Form7.class.getName()).log(Level.SEVERE, null, ex);
        }

        
                
	}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Vote Cast Demo EVM (Electronic Voting Machine)");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oem\\Documents\\NetBeansProjects\\com.mycompany_VotingSystem_jar_1.0-SNAPSHOT\\Images\\Rahul img.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 6, 181, 115));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oem\\Documents\\NetBeansProjects\\com.mycompany_VotingSystem_jar_1.0-SNAPSHOT\\Images\\Modi.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 127, 180, 133));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oem\\Documents\\NetBeansProjects\\com.mycompany_VotingSystem_jar_1.0-SNAPSHOT\\Images\\arvind-kejriwal.jpg")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 266, 251, 134));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oem\\Documents\\NetBeansProjects\\com.mycompany_VotingSystem_jar_1.0-SNAPSHOT\\Images\\Sukha img.jpg")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 411, 152, 134));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oem\\Documents\\NetBeansProjects\\com.mycompany_VotingSystem_jar_1.0-SNAPSHOT\\Images\\Nota img.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 551, 152, 107));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oem\\Documents\\NetBeansProjects\\com.mycompany_VotingSystem_jar_1.0-SNAPSHOT\\Images\\Hath Symbol.png")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 190, 110));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oem\\Documents\\NetBeansProjects\\com.mycompany_VotingSystem_jar_1.0-SNAPSHOT\\Images\\Kamal Sign.jpg")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 190, 120));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oem\\Documents\\NetBeansProjects\\com.mycompany_VotingSystem_jar_1.0-SNAPSHOT\\Images\\Charu image.jpg")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 190, 130));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oem\\Documents\\NetBeansProjects\\com.mycompany_VotingSystem_jar_1.0-SNAPSHOT\\Images\\Takri Symbol.jpg")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 220, 120));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oem\\Documents\\NetBeansProjects\\com.mycompany_VotingSystem_jar_1.0-SNAPSHOT\\Images\\Nota img.jpg")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 220, 110));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oem\\Documents\\NetBeansProjects\\com.mycompany_VotingSystem_jar_1.0-SNAPSHOT\\Images\\Voting Sign.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 140, 110));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oem\\Documents\\NetBeansProjects\\com.mycompany_VotingSystem_jar_1.0-SNAPSHOT\\Images\\Voting Sign.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 140, 120));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oem\\Documents\\NetBeansProjects\\com.mycompany_VotingSystem_jar_1.0-SNAPSHOT\\Images\\Voting Sign.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 140, 130));

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oem\\Documents\\NetBeansProjects\\com.mycompany_VotingSystem_jar_1.0-SNAPSHOT\\Images\\Voting Sign.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 140, 120));

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oem\\Documents\\NetBeansProjects\\com.mycompany_VotingSystem_jar_1.0-SNAPSHOT\\Images\\Voting Sign.png")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, 140, 110));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oem\\Documents\\NetBeansProjects\\com.mycompany_VotingSystem_jar_1.0-SNAPSHOT\\Images\\Arrow.jpg")); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 140, 110));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oem\\Documents\\NetBeansProjects\\com.mycompany_VotingSystem_jar_1.0-SNAPSHOT\\Images\\Arrow.jpg")); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 140, 100));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oem\\Documents\\NetBeansProjects\\com.mycompany_VotingSystem_jar_1.0-SNAPSHOT\\Images\\Arrow.jpg")); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, 140, 110));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oem\\Documents\\NetBeansProjects\\com.mycompany_VotingSystem_jar_1.0-SNAPSHOT\\Images\\Arrow.jpg")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 410, 140, 110));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oem\\Documents\\NetBeansProjects\\com.mycompany_VotingSystem_jar_1.0-SNAPSHOT\\Images\\Arrow.jpg")); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 540, 140, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 1050, 670));

        jLabel16.setBackground(new java.awt.Color(255, 51, 255));
        jLabel16.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel16.setText("    \"VOTING IS NOT ONLY OUR RIGHT - IT IS OUR POWER..\"");
        jLabel16.setOpaque(true);
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 1050, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        j=jLabel12;
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        Thread t=new Thread(this);
        t.start();
        
        int id= Form6.v_id;
        String n=Form6.v_name;
        String g=Form6.gen;
        //Form6.jComboBox1.removeItemAt(Form6.jComboBox1.getSelectedIndex());
        String x="Y";
        try {
            stmt.executeUpdate("update voters set VOTE='"+x+"' where VOTER_ID="+Form6.idd);
        } catch (SQLException ex) {
            Logger.getLogger(Form7.class.getName()).log(Level.SEVERE, null, ex);
        }
        String time=null,cand;
        try {
            ResultSet rs=stmt.executeQuery("select * from timeslot");
            while(rs.next())
            {
                if(rs.getString(1).equals("Y")  &&  rs.getInt(2)==8 && rs.getInt(3)==11)
                {
                    time="8-11";
                    stmt1.executeUpdate("update timeslot set NUMBER=NUMBER+1 where TIME_FROM =8 and TIME_TO=11");
                }
                if(rs.getString(1).equals("Y")  &&  rs.getInt(2)==11 && rs.getInt(3)==1)
                {
                    time="11-1";
                    stmt1.executeUpdate("update timeslot set NUMBER=NUMBER+1 where TIME_FROM =11 and TIME_TO=1");
                }
                if(rs.getString(1).equals("Y")  &&  rs.getInt(2)==1 && rs.getInt(3)==3)
                {
                    time="1-3";
                    stmt1.executeUpdate("update timeslot set NUMBER=NUMBER+1 where TIME_FROM =1 and TIME_TO=3");
                }
                if(rs.getString(1).equals("Y")  &&  rs.getInt(2)==3 && rs.getInt(3)==5)
                {
                    time="3-5";
                    stmt1.executeUpdate("update timeslot set NUMBER=NUMBER+1 where TIME_FROM =3 and TIME_TO=5");
                }
            }
            
            cand="RAHUL GANDHI";
            stmt.executeUpdate("insert into voting values ("+id+",'"+n+"','"+g+"','"+time+"','"+cand+"')");
            stmt.executeUpdate("update result set COUNT=COUNT+1 where CANDIDATE='RAHUL GANDHI'");
        } catch (SQLException ex) {
            Logger.getLogger(Form7.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        j=jLabel13;
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        Thread t=new Thread(this);
        t.start();
        
         int id= Form6.v_id;
        String n=Form6.v_name;
        String g=Form6.gen;
        String x="Y";
        try {
            stmt.executeUpdate("update voters set VOTE='"+x+"' where VOTER_ID="+Form6.idd);
        } catch (SQLException ex) {
            Logger.getLogger(Form7.class.getName()).log(Level.SEVERE, null, ex);
        }
        String time=null,cand;
        try {
            ResultSet rs=stmt.executeQuery("select * from timeslot");
            while(rs.next())
            {
                if(rs.getString(1).equals("Y")  &&  rs.getInt(2)==8 && rs.getInt(3)==11)
                {
                    time="8-11";
                    stmt1.executeUpdate("update timeslot set NUMBER=NUMBER+1 where TIME_FROM =8 and TIME_TO=11");
                }
                if(rs.getString(1).equals("Y")  &&  rs.getInt(2)==11 && rs.getInt(3)==1)
                {
                    time="11-1";
                    stmt1.executeUpdate("update timeslot set NUMBER=NUMBER+1 where TIME_FROM =11 and TIME_TO=1");
                }
                if(rs.getString(1).equals("Y")  &&  rs.getInt(2)==1 && rs.getInt(3)==3)
                {
                    time="1-3";
                    stmt1.executeUpdate("update timeslot set NUMBER=NUMBER+1 where TIME_FROM =1 and TIME_TO=3");
                }
                if(rs.getString(1).equals("Y")  &&  rs.getInt(2)==3 && rs.getInt(3)==5)
                {
                    time="3-5";
                    stmt1.executeUpdate("update timeslot set NUMBER=NUMBER+1 where TIME_FROM =3 and TIME_TO=5");
                }
            }
            
            cand="NARENDER MODI";
            stmt.executeUpdate("insert into voting values ("+id+",'"+n+"','"+g+"','"+time+"','"+cand+"')");
            stmt.executeUpdate("update result set COUNT=COUNT+1 where CANDIDATE='NARENDER MODI'");
        } catch (SQLException ex) {
            Logger.getLogger(Form7.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        j=jLabel14;
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        Thread t=new Thread(this);
        t.start();
        
         int id= Form6.v_id;
        String n=Form6.v_name;
        String g=Form6.gen;
        String x="Y";
        try {
            stmt.executeUpdate("update voters set VOTE='"+x+"' where VOTER_ID="+Form6.idd);
        } catch (SQLException ex) {
            Logger.getLogger(Form7.class.getName()).log(Level.SEVERE, null, ex);
        }
        String time=null,cand;
        try {
            ResultSet rs=stmt.executeQuery("select * from timeslot");
            while(rs.next())
            {
                if(rs.getString(1).equals("Y")  &&  rs.getInt(2)==8 && rs.getInt(3)==11)
                {
                    time="8-11";
                    stmt1.executeUpdate("update timeslot set NUMBER=NUMBER+1 where TIME_FROM =8 and TIME_TO=11");
                }
                if(rs.getString(1).equals("Y")  &&  rs.getInt(2)==11 && rs.getInt(3)==1)
                {
                    time="11-1";
                    stmt1.executeUpdate("update timeslot set NUMBER=NUMBER+1 where TIME_FROM =11 and TIME_TO=1");
                }
                if(rs.getString(1).equals("Y")  &&  rs.getInt(2)==1 && rs.getInt(3)==3)
                {
                    time="1-3";
                    stmt1.executeUpdate("update timeslot set NUMBER=NUMBER+1 where TIME_FROM =1 and TIME_TO=3");
                }
                if(rs.getString(1).equals("Y")  &&  rs.getInt(2)==3 && rs.getInt(3)==5)
                {
                    time="3-5";
                    stmt1.executeUpdate("update timeslot set NUMBER=NUMBER+1 where TIME_FROM =3 and TIME_TO=5");
                }
            }
            
            cand="KEJRIWAL";
            stmt.executeUpdate("insert into voting values ("+id+",'"+n+"','"+g+"','"+time+"','"+cand+"')");
            stmt.executeUpdate("update result set COUNT=COUNT+1 where CANDIDATE='KEJRIWAL'");
        } catch (SQLException ex) {
            Logger.getLogger(Form7.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        j=jLabel10;
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        Thread t=new Thread(this);
        t.start();
        
         int id= Form6.v_id;
        String n=Form6.v_name;
        String g=Form6.gen;
        String x="Y";
        try {
            stmt.executeUpdate("update voters set VOTE='"+x+"' where VOTER_ID="+Form6.idd);
        } catch (SQLException ex) {
            Logger.getLogger(Form7.class.getName()).log(Level.SEVERE, null, ex);
        }
        String time=null,cand;
        try {
            ResultSet rs=stmt.executeQuery("select * from timeslot");
            while(rs.next())
            {
                if(rs.getString(1).equals("Y")  &&  rs.getInt(2)==8 && rs.getInt(3)==11)
                {
                    time="8-11";
                    stmt1.executeUpdate("update timeslot set NUMBER=NUMBER+1 where TIME_FROM =8 and TIME_TO=11");
                }
                if(rs.getString(1).equals("Y")  &&  rs.getInt(2)==11 && rs.getInt(3)==1)
                {
                    time="11-1";
                    stmt1.executeUpdate("update timeslot set NUMBER=NUMBER+1 where TIME_FROM =11 and TIME_TO=1");
                }
                if(rs.getString(1).equals("Y")  &&  rs.getInt(2)==1 && rs.getInt(3)==3)
                {
                    time="1-3";
                    stmt1.executeUpdate("update timeslot set NUMBER=NUMBER+1 where TIME_FROM =1 and TIME_TO=3");
                }
                if(rs.getString(1).equals("Y")  &&  rs.getInt(2)==3 && rs.getInt(3)==5)
                {
                    time="3-5";
                    stmt1.executeUpdate("update timeslot set NUMBER=NUMBER+1 where TIME_FROM =3 and TIME_TO=5");
                }
            }
            
            cand="SUKHBIR BADAL";
            stmt.executeUpdate("insert into voting values ("+id+",'"+n+"','"+g+"','"+time+"','"+cand+"')");
            stmt.executeUpdate("update result set COUNT=COUNT+1 where CANDIDATE='SUKHBIR BADAL'");
        } catch (SQLException ex) {
            Logger.getLogger(Form7.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        j=jLabel15;
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        Thread t=new Thread(this);
        t.start();
        
         int id= Form6.v_id;
        String n=Form6.v_name;
        String g=Form6.gen;
        String x="Y";
        try {
            stmt.executeUpdate("update voters set VOTE='"+x+"' where VOTER_ID="+Form6.idd);
        } catch (SQLException ex) {
            Logger.getLogger(Form7.class.getName()).log(Level.SEVERE, null, ex);
        }
        String time=null,cand;
        try {
            ResultSet rs=stmt.executeQuery("select * from timeslot");
            while(rs.next())
            {
                if(rs.getString(1).equals("Y")  &&  rs.getInt(2)==8 && rs.getInt(3)==11)
                {
                    time="8-11";
                    stmt1.executeUpdate("update timeslot set NUMBER=NUMBER+1 where TIME_FROM =8 and TIME_TO=11");
                }
                if(rs.getString(1).equals("Y")  &&  rs.getInt(2)==11 && rs.getInt(3)==1)
                {
                    time="11-1";
                    stmt1.executeUpdate("update timeslot set NUMBER=NUMBER+1 where TIME_FROM =11 and TIME_TO=1");
                }
                if(rs.getString(1).equals("Y")  &&  rs.getInt(2)==1 && rs.getInt(3)==3)
                {
                    time="1-3";
                    stmt1.executeUpdate("update timeslot set NUMBER=NUMBER+1 where TIME_FROM =1 and TIME_TO=3");
                }
                if(rs.getString(1).equals("Y")  &&  rs.getInt(2)==3 && rs.getInt(3)==5)
                {
                    time="3-5";
                    stmt1.executeUpdate("update timeslot set NUMBER=NUMBER+1 where TIME_FROM =3 and TIME_TO=5");
                }
            }
            
            cand="NOTA";
            stmt.executeUpdate("insert into voting values ("+id+",'"+n+"','"+g+"','"+time+"','"+cand+"')");
            stmt.executeUpdate("update result set COUNT=COUNT+1 where CANDIDATE='NOTA'");
        } catch (SQLException ex) {
            Logger.getLogger(Form7.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Form7().setVisible(true);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Form7.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
